language: cpp
compiler:
    - clang++
os:
    - osx
before_install:
    - brew update
    - brew upgrade
    - brew install cmake
    - brew tap homebrew/science
    - brew install opencv
script: "sh ./.travis_build.sh"
